### ISSUE TITLE
Feature Request: Ability to Download Files

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#15]
When a user embeds a Google Doc, could there be a means of allowing the end-user/blog audience to download or create a copy of the document? 

If the URL could be made available in the header or footer, or possibly below the embed, then users could click the "anyone with the link can view" link and then create a copy to add to their Google Drive. This would be particularly helpful when teachers are creating templates that they want their students to be able to create a copy of.

**Comment by r-a-y** [comment]
The download option is probably possible.  Will look into this.

Not sure what "create a copy" means, but that sounds complicated :)

**Comment by mrjarbenne** [comment]
That's just an option the end user can trigger once it open in View Only mode on Google Drive. Nothing we need to account for on our end. That said, weird Google ninja trick, if you delete everything including the word "edit" from a share URL, and replace it with "copy" anyone who clicks on the link gets their own copy of the file, rather than it opening up as "view only".

Eg: 

https://docs.google.com/document/d/1QnnNC4_34MJR5dHpaR0yGVKhydMWEQILhx4PzTJuM2Y/edit?usp=sharing

vs

https://docs.google.com/document/d/1QnnNC4_34MJR5dHpaR0yGVKhydMWEQILhx4PzTJuM2Y/copy

**Comment by r-a-y** [comment]
Thanks for the ninja hack regarding the Copy mode!

I think I can add both link options to Google Docs Shortcode and GDrive can have additional options under the existing "Document Display Options" block.

Link will be manually inserted after the IFRAME.  They will not be styled and will rely on the active theme's CSS.

Does that sound okay?

**Comment by mrjarbenne** [comment]
Sounds magical

**Comment by r-a-y** [comment]
It looks like you cannot copy non-Google Doc items.  I'll probably 
restrict Copy to only Docs, Sheets and Slides.

**Comment by mrjarbenne** [comment]
That makes good sense.

**Comment by r-a-y** [comment]
I've added the download option for testing.  You might need to purge your cache for the JS to take place.  Give it a test with a few doc types and let me know if everything works.

There is a small bug with Shortcake though.  When you initially add the download link and later want to uncheck it using Shortcake, Shortcake does not remove the download link from the WYSIWYG editor.  However, the text editor correctly shows the updated content.

**Comment by mrjarbenne** [comment]
Wow. That's pretty awesome. Is the Shortcake bug something we need to report? Beyond that it looks great. I'm seeing the Add Download Link option on png files as well. Did you sort out extending the support beyond Google Drive native files (docs, sheets, slides)?

**Comment by mrjarbenne** [comment]
I'm seeing some inconsistency in the trigger keeping the Insert into Post button inactive in cases where the file is not public. It seems to be cropping up when a second document is being added to a post. In initial doc is fine, here's what I'm seeing in cases where a second document is added to the post:

http://www.screencast.com/t/JpZUdCTL

**Comment by r-a-y** [comment]
> Is the Shortcake bug something we need to report?

Yes, probably.  I'll do so once I figure out if has been fixed in the development version.

>  Did you sort out extending the support beyond Google Drive native files (docs, sheets, slides)? 

Download link works for all types.  It was the copy link that I said would work with native Google Drive types only.

> I'm seeing some inconsistency in the trigger keeping the Insert into Post button

Thanks.  Looking into this bug.

**Comment by r-a-y** [comment]
> I'm seeing some inconsistency in the trigger keeping the Insert into Post button

This should be fixed as of commit 382bfbb.
