### ISSUE TITLE
Restrict "Show Docs Header / Footer" option

### ISSUE THREAD

**Issue by r-a-y** [hwdsbcommons/gdrive#16]
I think I should only show this option if the Google Document is published.

The header / footer option does not work for link-shared documents ("Anyone on the web" and "Public on the web")..

**Comment by mrjarbenne** [comment]
That would explain why it seemed to be hit and miss. Thanks for the further research. This makes good sense.

**Comment by r-a-y** [comment]
Fixed in commit dd95ceb.  Made a typo in the commit message!

Make sure to purge your browser cache to test.
