### ISSUE TITLE
Sidebar z-index scrolling issue on mobile devices

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#17]
http://www.screencast.com/t/dZsPwWoDDm

**Comment by r-a-y** [comment]
I swear I fixed this before.  See #10.

Perhaps a latest version of WP broke the change.  I'll look into it a bit later on.

**Comment by mrjarbenne** [comment]
I'm not sure if I ever reported the scrolling thing, although you may have noticed and fixed it previously. Gremlins!
