### ISSUE TITLE
Search No Longer Working 

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#18]
The search functionality within gdrive takes you to a new post now, rather than searching Google in the mexp window. Search within the mexp-Vimeo plugin is functioning normally.

**Comment by r-a-y** [comment]
Should be fixed now.

This was due to the proposed changes to MEXP in the `js-override` branch.  Do a hard refresh to purge the JS and see if it works fo ryou now.

**Comment by mrjarbenne** [comment]
Thanks. That looks good too.
