### ISSUE TITLE
Don't render iFrame on Unsupported Formats

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#19]
Because we now have the ability to add a download link to a file format (something we didn't have when we first started working on this) it would make aesthetic sense to not render the iFrame in cases where the file format isn't a supported format.   

![2017-03-02_10-11-17](https://cloud.githubusercontent.com/assets/480667/23513025/adccb44a-ff30-11e6-97ca-63a61090d70b.png)

If the filename could be shown instead, that would be perfect. We don't need anything special in terms of a rendered icon. If the "Download" link could reflect the file name, that would be more than sufficient.

**Comment by mrjarbenne** [comment]
Rethinking this in the context of still needing the Pop Out button that appears in the iFrame. New issue forthcoming.

**Comment by r-a-y** [comment]
Depends on https://github.com/cuny-academic-commons/google-docs-shortcode/issues/10.

**Comment by mrjarbenne** [comment]
Now that https://github.com/cuny-academic-commons/google-docs-shortcode/commit/5305481ab94c2e4085a6fe6b34baab6f438017c1 has been merged, can we investigate adding a toggle to the sidebar to add the "hideiframe" shortcode attribute?

![2017-06-23_14-23-05](https://user-images.githubusercontent.com/480667/27495361-a1991108-581f-11e7-91cc-c0fae38b3729.png)

**Comment by r-a-y** [comment]
I've added the option and also updated Google Docs Shortcode on production as well.

Let me know if everything is working as expected.

**Comment by mrjarbenne** [comment]
Perfect. Is it possible to force the Download toggle on, if you switch the Embed frame off, otherwise nothing appears in the post at all.

**Comment by r-a-y** [comment]
Is having both the "Hide Embed Frame" and "Show Download Link" options redundant for generic file types when we've already determined that generic file types cannot be embedded properly?

Those options can probably be hidden for generic file types, so we can default the `hideiframe` option to `true` and the `downloadlink` option to `true` as well.  What do you think?

**Comment by mrjarbenne** [comment]
I think that captures nicely the initial push on this ticket which was attempting to avoid the google embed fail on non-google file types.

**Comment by mrjarbenne** [comment]
Perhaps we force "Show File Name" as well, so it's not just an icon and the uneditable "Download" text.

**Comment by r-a-y** [comment]
In the latest commits, I've decided to just hide the entire "Document Display Options" sidebar section for generic file types.  When you insert a generic file type into a post, the shortcode will automatically hide the embed frame, show the download link and show the filename.

Let me know what you think.

**Comment by r-a-y** [comment]
Going to close this one out.
