### ISSUE TITLE
Users No Longer Being Prompted to Auth Google

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#23]
I've had a couple reports of users who can't search or render their Google Drive in the MEXP panel. Investigating further has surfaced that they aren't authenticated with Google Drive anymore. Previously users who weren't authenticated were redirected to their BP profile to authenticate. That doesn't seem to be the case anymore.

**Comment by r-a-y** [comment]
Can you pass me the user IDs of some of the affected profiles?

I tried to load the Google Drive Gutenberg block and it asked me to "Set up Google Drive".  Clicking on that opened a new page to my profile's "Settings > General" page with the Google Drive icon.

I clicked on the Google Drive icon to start the set up and logged in with a Google account.  Google warned me that our Google Drive app is unverified.  I proceeded anyway and our GDrive plugin was able to save the authenticated token.  This is the part where users might be experiencing issues.  Can you see why our app is not verified?

Then I refreshed my Gutenberg page and was able to successfully connect to my Google Drive account via the GDrive Gutenberg block.

**Comment by mrjarbenne** [comment]
This wasn't in Gutenberg, but in the regular view. Users affected: akelly, sobreza. When they go to Insert from Google, they see they search and all options, rather than the blue button, but it doesn't search, and when you go to their profile, the Sign in with Google button is there, rather than the green banner indicating connection (I fixed it for a third user, so those two should still be experiencing the issue). 

I'm starting to think that it's not that the prompt isn't showing initially (I just tested with someone who had never forged the connection and they workflow worked for them), but perhaps the users are losing the connection (not sure how). 

I'm going to close this for now. It looks like if users are seeing the issue, they can manually visit their profile and reconnect. Maybe they are disconnecting from the Google side.

Not sure why the project isn't verifed. In the console settings, the project is owned by HWDSB. You are in as an owner too, with your gmail account, but I don't think that should be an issue.

**Comment by r-a-y** [comment]
> Maybe they are disconnecting from the Google side.

This seems like the correct reason why those users might be experiencing this specific issue.  If they disconnected manually from Google's side, then MEXP GDrive would have no idea that this occurred.

Hence, the logged-in search interface is still enabled.  Your instructions to disconnect and reconnect from the user's "Settings > General" page is the right thing to do in this use-case.
