### ISSUE TITLE
Layout Issue of Block

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#26]
The GDrive Block's button is overlapping the URL text box: 

![2019-08-31_11-54-00](https://user-images.githubusercontent.com/480667/64066417-3e9ef700-cbe7-11e9-9e60-3bc1769d4814.png)

**Comment by r-a-y** [comment]
I've pushed up some CSS changes on production.  Let me know if that fixes this issue.

**Comment by mrjarbenne** [comment]
Fixed. Thanks for that. Looks great!
